---
- name: Detecting existing PyPI installation
  ansible.builtin.stat:
    path: "{{ ara_api_venv_path }}"
  register: existing_pypi_install

- name: Notify about existing PyPI installation
  ansible.builtin.debug:
    msg: |
      You seem to have ARA-API installed via PyPI in the past, you might
      want to clean up that installation and migrate your data
  when: existing_pypi_install['stat']['exists']

- name: Override file locations with path in container
  ansible.builtin.set_fact:
    ara_api_database_name: "/opt/ara/ansible.sqlite"
    ara_api_log_dir: "/opt/ara/logs"
    ara_api_settings: "{{ ara_api_root_dir }}/settings.yaml"

- name: Ensure Podman Quadlets
  ansible.builtin.template:
    src: "{{ ara_api_quadlet }}"
    dest: "/etc/containers/systemd/{{ ara_api_quadlet }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  loop:
    - 'ara-api.container'
    - 'ara-api.volume'

- name: Ensure service
  ansible.builtin.systemd:
    name: ara-api-container.service
    state: started
    enabled: true
    daemon_reload: true
